[pytest]
testpaths = tests

python_files = test_*.py

python_functions = test_*

addopts =
    -ra
    --strict-markers
    --strict-config

filterwarnings =
    error

#What this does
#Searches only inside tests/
#Runs only files beginning with test_
#Treats warnings as errors
#Enables strict marker validation
#Displays a better test summary